version: v2beta1
name: alterconso

vars:
  RELEASE: local
  NAMESPACE: default
  STORAGE_PATH: /tmp/devspace-alterconso

images:
  alterconso:
    image: ghcr.io/gpenaud/alterconso
    context: .
    dockerfile: Dockerfile
    tags:
      - dev-latest

functions:
  create_storage_path: mkdir -p ${STORAGE_PATH}
  clean_storage_path: sudo rm -rf ${STORAGE_PATH:-/void}

pipelines:
  deploy: |-
    create_storage_path
    create_deployments --all
  purge: |-
    purge_deployments --all
    clean_storage_path

deployments:
  dockerconfigjson:
    kubectl:
      inlineManifest: |-
        apiVersion: external-secrets.io/v1
        kind: ExternalSecret
        metadata:
          name: regcred
          namespace: ${NAMESPACE}
        spec:
          refreshInterval: 1h
          secretStoreRef:
            kind: ClusterSecretStore
            name: kube-system-secret-store
          target:
            name: regcred
            template:
              type: kubernetes.io/dockerconfigjson
          dataFrom:
            - extract:
                key: regcred
  alterconso:
    namespace: ${NAMESPACE}
    helm:
      chart:
        path: ./helm
      valuesFiles:
        - helm/values.yaml
      values:
        webapp:
          image:
            version: dev-latest
        database:
          persistentVolume:
            local:
              path: ${STORAGE_PATH}

# ------------------------------------------------------------------------------ #

dev:
  webapp:
    namespace: ${NAMESPACE}
    labelSelector:
      app.kubernetes.io/instance: ${RELEASE}
      app.kubernetes.io/name: alterconso
      app.kubernetes.io/component: alterconso-webapp
    containers:
      webapp:
        command: ["sh", "-c", "/usr/sbin/apache2ctl -D FOREGROUND"]
  database:
    namespace: ${NAMESPACE}
    labelSelector:
      app.kubernetes.io/instance: ${RELEASE}
      app.kubernetes.io/name: alterconso
      app.kubernetes.io/component: alterconso-database

# ------------------------------------------------------------------------------ #

commands:
  recreate-cluster:
    description: Recreate the cluster with Ansible playbook 
    command: |-
      ANSIBLE_CONFIG=${ANSIBLE_PATH}/ansible.cfg ansible-playbook ${ANSIBLE_PATH}/playbooks/install-k3s-lab.yml
  inject:
    description: Inject a 6-month old backup into database.  
    command: |-
      kubectl exec -i statefulsets/local-alterconso-database -- mysql -u root -proot --binary-mode --max_allowed_packet=64M db < utilities/dump.sql
    after: |-
      sudo rm -rf ${STORAGE_PATH:-.}/*
  debug:
    description: Dumps the current helm templates.
    command: helm template --debug ./helm/
  test:
    description: A dry-run of current helm package.
    command: helm install --dry-run --debug local ./helm/
  package:
    description: Package Helm source code 
    command: |-
      helm package ./helm/ --destination ./../helm-charts
      helm repo index ./../helm-charts
  encrypt:
    description: Encrypt argument with kubeseal controller
    command: |-
      echo -n $@ | /usr/local/bin/kubeseal \
        --context local --namespace kube-system --raw --scope cluster-wide \
        --controller-namespace=kube-system
